import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  imgContainer: {
    // flex: 0.4,
    height: 246,
    backgroundColor: '#0A4975',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  registerContainer: {
    marginTop: -55,
    margin: 20,
    padding: 20,
    paddingHorizontal: 25,
    height: 750,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    shadowColor: '#00000040',
    elevation: 20,
    shadowRadius: 3,
  },
  registerTitle: {
    fontSize: 30,
    fontFamily: 'Nunito-SemiBold',
    // textAlign: 'center',
    color: '#000000',
  },
  inputHeading: {
    color: '#000000A8',
    fontFamily: 'Nunito-Regular',
    fontSize: 18,
    marginTop: 15,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#0A49755E',
    borderRadius: 8,
    paddingLeft: 15,
    marginTop: 5,
  },
  passwordContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#0A49755E',
    borderRadius: 8,
    marginTop: 5,
  },
  eyeLogo: {
    margin: 15,
    marginRight: 15,
  },

  registerButton: {
    backgroundColor: '#FFBD59',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    // height: 40,
    paddingVertical: 10,
    marginTop: 20,
  },
  registerText: {
    color: '#000000',
    fontSize: 16,
    fontFamily: 'Nunito-SemiBold',
  },
  haveAccount: {
    color: '#0A4975',
    fontFamily: 'Nunito-Regular',
    fontSize: 14,
    alignSelf: 'center',
    marginTop: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalSubContainer: {
    backgroundColor: '#FFFFFF',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    borderRadius: 10,
    elevation: 20,
  },
  modalText: {
    fontFamily: 'Nunito-Medium',
    fontSize: 19,
    color: '#000000A8',
    textAlign: 'center',
  },
  modalContinueButton: {
    backgroundColor: '#FFBD59',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 10,
    marginTop: 15,
    width: '100%',
  },
  continueText: {
    color: '#000000',
    fontSize: 16,
    fontFamily: 'Nunito-SemiBold',
  },
});
export default styles;
